### ISSUE TITLE
Availability of fine-tuned summarization models

### ISSUE THREAD

**Issue by marksverdhei** [navjordj/Master-Norwegian-Abstractive-Summarization#2]
Hi, I was just wondering if the models for summarization are available somewhere.
Didn't find anything here or on the hugggingface hub, so i'm wondering if this was a conscious decision or not

**Comment by jkorsvik** [comment]
Hello, Sorry for the late reply! Yes, exists with out respective usernames, the same on huggingface and github

They are linked to in the paper: 
APPENDIX B
DATASET AND MODEL URLS
Page 84
@marksverdhei

**Comment by marksverdhei** [comment]
Thanks!
